version: '3.7'
services:
    nginx:
        image: nginx:1.17.6
        container_name: task-manager-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/task-manager
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
            - .docker/nginx/logs/:/var/log/nginx/
        depends_on:
            - php

    php:
        build: .docker/php
        container_name: task-manager-php
        env_file:
             - .env.local
        volumes:
            - ./:/var/www/task-manager
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        links:
            - db

    db:
        image: mysql:8.0.18
        container_name: task-manager-mysql
        ports:
            - "3311:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: task_manager
            MYSQL_USER: task_manager
            MYSQL_PASSWORD: task_manager_password
        volumes:
            - .docker/db/data:/var/lib/mysql
